In [7]:
import pandas as pd
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [8]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [9]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [15]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

,PassengerId,Name,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male,female,male
0,1,"Braund, Mr. Owen Harris",3,22.0,1,0,A/5 21171,7.2500,NaN,S,False,True,False,True
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,True,False,True,False
2,3,"Heikkinen, Miss. Laina",3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False,True,False

In [18]:
inputs.drop(['Sex'],axis='columns',inplace=True)
inputs.head(3)

KeyError: "['Sex' 'male'] not found in axis"

In [13]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [14]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean)
inputs.head(3)

,PassengerId,Name,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,"Braund, Mr. Owen Harris",3,22.0,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,True,False
2,3,"Heikkinen, Miss. Laina",3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False